name: "action-dump-sqlite"

author: "ryohidaka"

description: "GitHub Actions to generate SQLite database dump files."

branding:
  color: green
  icon: send

inputs:
  version:
    description: "SQLite version to install (optional)"
    required: false
    default: "latest"

  db:
    description: "The name of the SQLite database file to use."
    required: true

  output:
    description: "The output file name for the SQL dump."
    required: true

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Setup SQLite environment
      uses: ryohidaka/action-setup-sqlite@v1.2.0
      with:
        version: ${{ inputs.version }}

    - name: Dump tables to SQL
      run: |
        $GITHUB_ACTION_PATH/scripts/dump.sh \
          ${{ inputs.db }} \
          ${{ inputs.output }}
      shell: bash
