name: "Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SQLite environment
        uses: ryohidaka/action-setup-sqlite@v1.2.0

      - name: Create sample.db and add tables
        run: |
          sqlite3 sample.db <<EOF
            CREATE TABLE users (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              name TEXT NOT NULL,
              email TEXT NOT NULL
            );
            CREATE TABLE orders (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              user_id INTEGER,
              product TEXT NOT NULL,
              amount INTEGER NOT NULL,
              FOREIGN KEY (user_id) REFERENCES users (id)
            );
            INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');
            INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane@example.com');
            INSERT INTO orders (user_id, product, amount) VALUES (1, 'Product A', 3);
            INSERT INTO orders (user_id, product, amount) VALUES (2, 'Product B', 2);
          EOF

      - name: Run Dump SQLite for users
        uses: "./"
        with:
          db: "sample.db"
          output: "users.sql"
          tables: "users"

      - name: Check Dump file for users
        run: cat users.sql

      - name: Run Dump SQLite for all tables
        uses: "./"
        with:
          db: "sample.db"
          output: "sample.sql"

      - name: Check Dump file
        run: cat sample.sql
